### ISSUE TITLE
How to modify the style of navigation on the mobile device?

### ISSUE THREAD

**Issue by dbarobin** [mmistakes/so-simple-theme#112]
I've already been used the old version of `so simple theme`, it worked well on the mobile device. But I upgraded to the latest version of `so simple theme`, the style of navigation turned terrible. When I clicked the **MENU BUTTON**, all of screen covered with black background, it was poor UX truly. I want to modify the style of navigation on the mobile device, to achieve this effect: when I click the **MENU BUTTON**, all of category display with narrow black background. What I should do?  Please help me.

My GitHub pages repo: [dbarobin.github.io](https://github.com/dbarobin/dbarobin.github.io)
And this is my personal domain associated with the Github pages repo: http://dbarobin.com/

Thanks! Have a nice day.

**Comment by mmistakes** [comment]
If you don't like the style of the navigation you'll have to hack up the CSS to suit your needs. On the classes and elements I start with the mobile styles and then add on or override them using media queries to take care of the larger screen sizes.

Personally I don't think the navigation is poor and like the overlayed menu. By increasing the font sizes tap targets of each menu item it makes them more friendly for small touch screens. Sorry that the new "style" isn't your taste, but it's not bad UX.

Because you have your site under version control with Git you can easily revert back. If you liked the older style better I'd suggest you do that and then just cherry pick newer commits I've made to repo to fix or update other things.

**Comment by dbarobin** [comment]
Thanks! I'll try.
