### ISSUE TITLE
Usage of site.url

### ISSUE THREAD

**Issue by mlafeldt** [mmistakes/so-simple-theme#113]
Hi,

I've got a question regarding `site.url`, which is used all over the codebase: how can I set it to a meaningful value (i.e. the URL where the site gets deployed) without losing the ability to preview my site locally with `jekyll serve`?

I'm migrating my blog from the [Left theme](https://github.com/holman/left) where this wasn't a problem as `site.url` is only used in feed.xml and sitemap.xml. In the HTML itself, only relative links are used.

**Comment by mmistakes** [comment]
There's a few ways you can do it.

1. Set `site.url` with a value that matches the domain you deploy to. When testing locally comment out that line (eg: `# url: http://yourdomain.com`) so it is ignored. Everything will work as expected with the exception of maybe the home link in the top nav (not a big deal, it works in production).
2. Use 2 different sets of Jekyll config files, one with the production domain and the other for local development. This is how I do it.

For example. My [`_config.yml`](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/_config.yml) has `url: https://mademistakes.com` and then I created another file called [`_config-dev.yml`](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/_config-dev.yml) that has `url: http://localhost:4000` and some other dev friendly settings related to a few plugins I use. When I'm testing I run `jekyll serve --config _config-dev.yml` to start up a Jekyll server using the my dev configurations. You can name the file whatever you want.

When deploying I run Jekyll as I normally would and that uses the default `_config.yml` file.

**Comment by mlafeldt** [comment]
I guess I can live with option 2. I'm using Rake anyway, so I could generate a `_config.yml` with `site.url` set to a proper value. Should work, although it's not super elegant.

Thanks!

**Comment by mmistakes** [comment]
You could remove `{{ site.url }}` in the various `_layouts` and `_includes` if you really want to streamline things. I went with absolutes because I kept seeing broken assets (CSS and JS) on various pages depending on what type of permalink structure being used. Things seemed to get messy when nesting down into subfolders. Absolutes fixed all that and eliminated me having to sound like a broken record everytime a GH issue came up with the same exact problem.

If your permalink structure is pretty flat you shouldn't have any problems going relative. The only place it really matters is in the feeds. A lot of feed readers have problems with relative URLs and need absolutes.

**Comment by mlafeldt** [comment]
Yes, I also wanted to check whether I can remove most occurrences of `site.url` altogether.

Thanks for your explanation.
