### ISSUE TITLE
How to make the content of post searchable?

### ISSUE THREAD

**Issue by dbarobin** [mmistakes/so-simple-theme#116]
I noticed that the author of `So Simple Theme` turned **Simple-Jekyll-Search** to **jekyll-search**, but I was confused. Except the style of search feature changed, nothing changed. I tried to use the search feature of new `So Simple Theme` demo, but I couldn't get the content of post either. So I don't want to synchronize this change.

I intend to know why the author of `So Simple Theme` did this change. And I want to figure out how to make the content of post searchable.

Thanks!
Have a nice day.

Robin

**Comment by mmistakes** [comment]
Post content was never searchable. The theme has always used a very basic search script and JSON to index just post titles.

You can modify `search.json` to include post content to make that searchable instead of `post.excerpts` but I didn't do that because I found it made the feature extremely fragile. Specifically if you include code snippets in your posts, it breaks the JSON and I couldn't find a good way around it that worked in every use case.

The framework is there for you to build off of and enhance for your own site. In this revised search script I included pages in the `search.json` file, previously only posts were indexed. Take a look at that file and it should be pretty obvious what content is being included in the search index. Just be aware you'll have to do a lot of content manipulation to avoid quotes and apostrophes that might break it.

There are [better search options for Jekyll](https://github.com/slashdotdash/jekyll-lunr-js-search), but it requires a plugin and those don't work with GitHub hosted sites --- which is a big portion of the theme's user base.

**Comment by dbarobin** [comment]
Thanks!
