### ISSUE TITLE
Featured Image on list of posts

### ISSUE THREAD

**Issue by pathumego** [mmistakes/so-simple-theme#126]
Hi.. is it possible to have a featured image for each post on the list of posts? Im looking for something that has this potion.. is it doable? if so just tell me how to.. and I will get it done :) Thanks

**Comment by mmistakes** [comment]
Sure anything is possible.. how comfortable are you with HTML and Liquid? You'll have to modify the themes layouts to include the featured images. Start by looking at the Liquid I'm using in the [`post`](https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/post.html) and [`page`](https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/page.html) layouts and adapt it for the post list pages.

```
{% if page.image.feature %}<img src="{{ site.url }}/images/{{ page.image.feature }}" class="entry-feature-image" alt="{{ page.title }}">{% endif %}
```

You'll likely have to mess with the stylesheets too since the post list pages were designed to just be a list. If you need more ideas my [HPSTR theme](https://github.com/mmistakes/hpstr-jekyll-theme) displays feature images on both post list pages and the single pages.

**Comment by domofactor** [comment]
I actually did something similar by yanking some of @mmistakes code out of the [Skinny Bones](https://github.com/mmistakes/skinny-bones-jekyll) Theme.

http://seishunspirit.com
using these two files as a reference:

https://github.com/domofactor/SeishunSpirit/blob/gh-pages/index.html

https://github.com/domofactor/SeishunSpirit/blob/gh-pages/_includes/post-grid.html

**Comment by pathumego** [comment]
Thanks Guys! Will update you on the progress :)
