### ISSUE TITLE
Index Page Feature Overlay

### ISSUE THREAD

**Issue by ahmadgit** [mmistakes/so-simple-theme#132]
Hi Michael ... How is it possible to overlay the feature image with text or links such as the one done in skinny bones (http://mmistakes.github.io/skinny-bones-jekyll/)? When I try to add a feature to the index page, it completely covers the text. How should I change the sass file to allow for overlay? Thanks

**Comment by mmistakes** [comment]
There's no quick answer to that one. There's a lot of custom CSS going on that is very different with Skinny Bones. To match the presentation there you'll have to do a lot of altering to the stylesheets and that may or may not be easy for you depending on how comfy you are with CSS/Sass.

Other than that the best I can offer is to use Skinny Bones instead if you like how the feature images are treated there.

**Comment by ahmadgit** [comment]
I see. I can make the feature image's position relative and then put some text on top of it by providing absolute coordinates. However when the user zooms in/out it does not scale properly. Is it possible for you to give me some general information of how to achieve this?

**Comment by mmistakes** [comment]
That's exactly how I'm doing it on my site. I have an element with `position: relative` that wraps the text elements I want to overlap the image. Those are then `position: absolute` with various `top`, `left`, `bottom` coordinates for placement.

It's not the easiest thing to get right especially when you factor in different screen sizes. I do a lot of font size changes at various screen widths using media queries to avoid any weird line breaks from occurring but it's far from perfect. All it takes is a really short title or really long one to throw it all out of whack.

Not sure what's going on with the zoom stuff. If done right the text should scale proportionally with everything else on the page.

Also now that I think about it Skinny Bones doesn't have any text that overlays images. On the demo site I did it with the lead in block on the homepage, but that's poorly executed. That's why I didn't document it or include it in the master branch.

A better example is my personal site [Made Mistakes](https://mademistakes.com). Take a look there to see how I'm positioning text absolutely over the feature images.

**Comment by ahmadgit** [comment]
Alright thanks a lot for the explanation.
