### ISSUE TITLE
Add sidebar for categorization of blogs

### ISSUE THREAD

**Issue by Faiz7412** [mmistakes/so-simple-theme#133]
A blogger would like if their audience can easily navigate through their posts. Nobody wants to go back in time and see posts by ordered by date. What matters is the category they are in for a reader.

**Comment by mmistakes** [comment]
I purposely left extra fluff like this off to avoid littering things up and keep the attention on the main content block. The sidebar's primary purpose is as an "author aside" with bio photo, published date, and social sharing (which I reluctantly added due to popular demand).

Above the post title there are links back to tag indexes (see image below) if you assigned any in the YAML Front Matter. My intention was to have others modify the source to fit their needs and build off of versus me cramming it full of noise. You can certainly edit the post layout to display categories in place of tags if that's how your content is grouped.

![screen shot 2015-03-20 at 9 06 20 pm](https://cloud.githubusercontent.com/assets/1376749/6763126/e033e254-cf45-11e4-8e48-ec4fe167ecfc.png)

Also, I didn't want to put too much focus on category and tag pages because they're challenging to create for most Jekyll users. Since a good chunk of those using the theme are free hosting on GitHub Pages, the option to use plugins that autogenerate category and tag pages is out of the question. Sure some will manually create those pages if they have a handful of categories/tags, but most will not.

Keep things simple is the philosophy here :wink:

**Comment by Faiz7412** [comment]
I really appreciate your work Michael. It's great. I agree, the simpler it is, the better. Medium.com's success is primarily because it is simple and elegant. 
I am loving your work already.
I'm facing some technical glitches with so-simple. Is there any way I can PM you?

**Comment by mmistakes** [comment]
Technical glitches with the theme or with Jekyll? [Jekyll Talk](https://talk.jekyllrb.com/) is a good place to ask for help on the later.

**Comment by Faiz7412** [comment]
Glitches with theme. Css doesn't load. I forked your repo and downloaded the zip. Launching index.html, this is what shows up.
![capture](https://cloud.githubusercontent.com/assets/8874731/6780954/a049afc4-d18f-11e4-9e16-5f83ecf9d0f3.JPG)

I cross verified if there is some problem on my pc, using this https://github.com/plusjade/jekyll-bootstrap
And it shows up perfectly. 
What could be the problem?

**Comment by mmistakes** [comment]
It's not the theme, you're not using Jekyll properly. That `index.html` file you're trying view in your browser is the source file before it's been processed by Jekyll. The tell-tale sign is it still has the YAML Front Matter and Liquid template code and hasn't run through Jekyll yet and built into a production ready HTML file.

You need to run `jekyll serve` and then open your browser to `http://localhost:4000` to properly view it. The processed `index.html` file will be in the `_site` folder if you've done it correctly. That's the file you want to look at...

**Comment by Faiz7412** [comment]
oh.. I see. 
Really sorry to bother you. I didn't have enough time to learn in-depth about jekyll. I prefer doing things the hacker way these days in order to move fast. 
What confused me was when I opened index.html file of jekyll bootstrap  ( https://github.com/plusjade/jekyll-bootstrap ) it loaded perfectly. I had a feeling that I'm doing something wrong. But then I guessed there could also be some problem in theme and I should report it so that you can check. 
Anyway, thanks ! Really appreciate your work.
Have a nice day.
