### ISSUE TITLE
Google Analytics Script provided in script.html

### ISSUE THREAD

**Issue by blunderboy** [mmistakes/so-simple-theme#151]
The following piece of code is provided in script.html for including Google Analytics account:

<hr>
var _gaq = _gaq || [];
 var pluginUrl = '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
  _gaq.push(['_require', 'inpage_linkid', pluginUrl]);
  _gaq.push(['_setAccount', '{{ site.owner.google.analytics }}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
<hr>

However, if I see tracking code in actual Google Analytics account. It is different which looks something like:

<hr>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-****-*', 'auto');
  ga('send', 'pageview');
<hr>
What is the difference between both ? How should I integrate the GA account ?

**Comment by mmistakes** [comment]
The theme is using the older tracking code and the one you posted is the newer [Universal Analytics](https://developers.google.com/analytics/devguides/collection/upgrade/?hl=en_US) script. I'm not sure if Google is requiring it yet or if it's been rolled out to all accounts which is why the theme still uses the older one.

To update your site you can replace the tracking code in `scripts.html` with the one Google gives you. If you want you can replace `UA-***-` with `{{ site.owner.google.analytics }}` if you have it set in your `_config.yml` and would rather manage it there. But since it won't likely ever change it's probably not necessary.

**Comment by blunderboy** [comment]
@mmistakes Great as expected..You can close this issue now. Although I wanted to ask one more thing but probably I should open another issue instead of polluting this one. I am closing this one.

**Comment by mmistakes** [comment]
If it's related to the GA script then feel free to ask here. Otherwise a
new issue would probably be best.
