### ISSUE TITLE
How to get latest updates from so-simple-theme

### ISSUE THREAD

**Issue by blunderboy** [mmistakes/so-simple-theme#152]
@mmistakes First of all, thanks for such a beautiful theme.
I have downloaded the theme and setup blog over it but I need to know the best practice I should follow to get all the latest changes being publshed to the repo.

I needed some of the following changes:

1. Renames site.url to site.baseurl everywhere in order to make it work globally
2. Some custom changes in _includes/*.html
3. Removed sample posts

If I pull latest changes, I am sure I will getting lots of merge conflicts. What is the best practice to tackle that ?

**Comment by mmistakes** [comment]
Thanks!

To answer your question Jekyll "themes" are a complete mess. There really is no good way to handle it since none of these repos are actual themes. At the end of the day they're just some ones Jekyll site with a few defaults set to hopefully make it easier for someone else to fork and use.

You can try and pull in changes but like you mentioned you'll most likely be dealing with a ton of merge conflicts on all the changes you made.

If the changes were minimal it's probably easier to fork the latest So Simple repo, dump the sample posts and other stuff, and pull in your content and custom includes.

I don't know if you've looked at the [Octopress](https://github.com/octopress) set of tools that augment Jekyll sites. It handles themes in a great way by making them Ruby gems you can install. I'd like to do that with my repos but waiting to see if that gets any traction with the community and if it's supported by GH-Pages before I put anytime into it.
