### ISSUE TITLE
Include ipython notebooks in post

### ISSUE THREAD

**Issue by sachinruk** [mmistakes/so-simple-theme#170]
I want to try and include my ipynb in my blog post which renders perfectly on github: https://github.com/sachinruk/sachinruk.github.io/blob/master/_posts/Stats%20Blog/CRP.ipynb

I was wondering if there was a method to include this in the posts. I tried copying the raw elements of the .ipynb to my post except it spat out jibberish: https://sachinruk.github.io/blog/Chinese-Restaurant-Process/

Otherwise is there a 'cheat' method like using iframe somehow to render it inside the post?

Thanks in advance.

**Comment by mmistakes** [comment]
Pasting the raw content into your post isn't going to work because Markdown will just spit it back out as plain text. You'll likely need some sort of plugin/converter/library/etc to process it into HTML for you. 

Since I'm not familiar with ipynb can't really help you there. Perhaps try the [Jekyll Talk](https://talk.jekyllrb.com/) forums to see if anyone else has done what you're asking.
