### ISSUE TITLE
Jekyll ignoring filenames containing `less`

### ISSUE THREAD

**Issue by ShawnStrickland** [mmistakes/so-simple-theme#202]
I noticed a weird bug where, after compiling a folder structure for categories like `/lessons` was not available. It would always lead to a 404. Changing the naming to something like `/tutorials`, however works just fine.

Can you reproduce?

**Comment by mmistakes** [comment]
Does `_site/lessons/index.html` exist? If not then you have to create one since Jekyll doesn't do that for you. 

The only other thing I can thing of is a change in Jekyll's core with how trailing slashes are handled. Bump,around that repo in the closed issues as problems around it have come up a lot since Jekyll hit v3.

Without seeing how you have everything setup I really can't speculate on what's wrong. If you have a public repo that would be helpful.

**Comment by ShawnStrickland** [comment]
It didn't exist; but I was under the assumption that this would be created for me, since adding a top-level folder, with an `index.md` inside seemed to tell Jekyll enough to generate the correct URL/pages. I think this is a fringe case, I'll close for now and re-open if I truly can't get it to work after a bit more understanding of Jekyll's generator.

**Comment by mmistakes** [comment]
Jekyll only creates what you tell it to. Looking at your repo you don't have a `/lessons/index.md` file which explains why you don't see it in the compiled version.

I do see you do have `/tutorials/index.md` so you've done some of the work. If you take that page, duplicate it for Lessons, and change `{% for post in site.categories.tutorials %}` to `{% for post in site.categories.lessons%}` you'll be good to go and get something at `/lessons` on your compiled site.

**Comment by ShawnStrickland** [comment]
Take a look at my repo, I do this but there's still a 404 error after creating the appropriate files in `/_posts` and `/lessons`

**Comment by mmistakes** [comment]
Ok I see what problem is now. In `_config.yml` there's an exclude line and in that array I have `less` to ignore `.less` files. But what's going on is it's ignoring anything that starts with `less` so that's why your Lessons page isn't being built.

Either remove `less` from the config or add a period in front of it like this:

```
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
```
