### ISSUE TITLE
Theme is not showing up as project page on Github Pages 

### ISSUE THREAD

**Issue by doka** [mmistakes/so-simple-theme#215]
Applying hint of #211, the theme runs nicely on Github Pages if it's setup as users or organizations pages, but links are still broken if the site is setup as project page.

**Comment by mmistakes** [comment]
The [theme's demo site](https://github.com/mmistakes/so-simple-theme/tree/gh-pages) is setup as a GitHub Project and works fine. `baseurl` could be added to all the relevant links but would need both `url` and `baseurl` to work in all situations. Otherwise it breaks.

For projects you just need the add the repo name to `url` since I haven't added `baseurl`.

Eg. `url: https://mmistakes.github.io/so-simple-theme`

**Comment by doka** [comment]
OK, thanks!
