### ISSUE TITLE
CORS issue for Search (GitHub pages deployment with custom domain)

### ISSUE THREAD

**Issue by nitya** [mmistakes/so-simple-theme#228]
I love this theme and am planning to use it for a couple of projects.

I recently forked and configured it to use with a GitHub pages hosted site (let's call it "abc.github.io"). The deployment was painless and worked out well.

I then updated the repo to use a custom domain (let's call it "xyz.me") that I registered via Google Domains. However I noticed that GitHub does not allow me to "Enable HTTPS" on my hosted pages now that I have a custom domain.

The site itself seemed to be functioning fine. Until I tried using the search capability. 

At this point I get a CORS message as follows: (domain names were changed to reflect the ones above but the message itself is the same) 

> XMLHttpRequest cannot load https://abc.github.io/search.json. Redirect from 'https://abc.github.io/search.json' to 'http://xyz.me/search.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Note: 
This message appears when I go to "http://xyz.me/search/" and enter a search term - but I am not sure where or why the "https" usage occurs. Directly accessing the "http://xyz.me/search.json" works though. Any suggestions on how I can debug/fix this?

**Comment by mmistakes** [comment]
I think what you want is to change your `url` in _config.yml. Without seeing your source I'm guessing you have it set as `url: https://abc.github.io`. Which prepends every asset with that... `{{ site.url }}/whatever.ext`

So when you hit your search page and hit submit from `http://xyz.me/search/` it's requesting `https://abc.github.io/search.json` which in the browser's eyes is a big security no-no because of cross-domain policies. If you example the page source you can confirm if this is true.

What you want is to set to match whatever your final domain is... which I believe would be `url: http://xyz.me`

Your issue is more of a web dev thing than anything related to the theme. I'd suggest trying Stackoverflow or a similar forum to help tackle your CORS issues.

**Comment by nitya** [comment]
Doh! 

Yes. It was the url in _config.yml. I had made that change before, committed it, then reversed it in a subsequent commit and never noticed. 

Definitely a web issue and not theme related -- apologies for posting it here, but hopefully useful to others. Many thanks for the fast response!!
