### ISSUE TITLE
site.url is always 0.0.0.0 instead of my defined value

### ISSUE THREAD

**Issue by vincentkwok** [mmistakes/so-simple-theme#229]
I am beginner of this theme, and would like to apply this theme for my existing blog. However, the `site.url` is always 0.0.0.0, even though I defined in `_config.yml`. It keeps confusing me. 

Also, when I would debug myself, I found abnormal output in `jekyll serve`:
```
fetch http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
OK: 255 MiB in 72 packages
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 2.0.5
Using colorator 1.1.0
Using ffi 1.9.17 (was 1.9.14)
Using forwardable-extended 2.6.0
Using addressable 2.5.0 (was 2.4.0)
Using pathutil 0.14.0
Using rb-fsevent 0.9.8 (was 0.9.7)
Using kramdown 1.13.2 (was 1.12.0)
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.14.3
Using sass 3.4.23 (was 3.4.22)
Using rb-inotify 0.9.8 (was 0.9.7)
Using multipart-post 2.0.0
Using jekyll-sass-converter 1.5.0 (was 1.4.0)
Using listen 3.0.8
Using faraday 0.11.0 (was 0.9.2)
Using jekyll-watch 1.5.0
Using sawyer 0.8.1 (was 0.7.0)
Using jekyll 3.4.0 (was 3.2.1)
Using octokit 4.6.2 (was 4.3.0)
Using jekyll-feed 0.8.0 (was 0.7.0)
Using jekyll-sitemap 1.0.0 (was 0.11.0)
Using jekyll-gist 1.4.0
Bundle updated!
Configuration file: /srv/jekyll/_config.yml
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 14.834 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
Configuration file: /srv/jekyll/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

I wonder 2 things:
1. Where are those fetch defined, and what do they actually do?
```
fetch http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
```

2. I tried to removed Gemfile & Gemfile.lock. However, they are generated automatically. Where are those procedure defined as well? I did global search but find nothing about that.

**Comment by mmistakes** [comment]
No idea on what that fetch stuff is about. My guess it has something to do with how you installed Jekyll, would it happen to be the Docker version? Those fetch URLs appear to be hitting @envygeek's, and he might be able to shed some light on what's going on.

The reason your `site.url` isn't taking is due to a new `jekyll serve` behavior. By default it overrides anything you place in `url` in your **_config.yml**. If you run `jekyll build` it will use whatever value you've set.

I'd encourage you to ask for Jekyll related help on the [talk forum](https://talk.jekyllrb.com/). You'll get way more insight on how all this works as it isn't really specific to this theme.

**Comment by envygeeks** [comment]
On Point 1: We it the mirror server (those fetches are `apk` in Alpine asking my server for a list of the latest packages for Alpine.) When we `gem install`, because we have no idea what's going on in your Gemfile, we always install packages that will help a little bit: https://github.com/jekyll/docker/blob/master/repos/jekyll/copy/all/usr/local/bin/jekyll#L36 and we also support `.apk` files to install packages that Alpine supports if you have specific needs for specific gems.

On Point 2 (the main point of this ticket) our image does not allow you to customize the binding IP, and we intentionally throw out your request to set it and override it inside of the image with a user-proof value, you need to do that with Docker, not with Jekyll because doing it in Jekyll will only prevent Docker from routing it.  You need to externally route it with Docker using your `-p` on the `docker run` or via `ports` in your Docker Compose.
