### ISSUE TITLE
Error on gitpages jekyll

### ISSUE THREAD

**Issue by vikmn** [mmistakes/so-simple-theme#232]
Hi,
I am trying to apply the theme to an existing blog but seem to encounter the error
Undefined mixin 'box-sizing'. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/
I have not built the site locally and am relying on git to pick it up for me but have encountered the error which has resulted in failure. pointers on what i might have missed out?

**Comment by mmistakes** [comment]
I would suggest building locally as it'll give you a better error message to clue you in what Sass file and where you're having the issue.

Pretty sure the `box-sizing` mixin it's referencing above is coming from [Bourbon](http://bourbon.io/) (found in [`_sass/vendor/bourbon/`](https://github.com/mmistakes/so-simple-theme/tree/master/_sass/vendor/bourbon)). Either it's missing or the paths changed and that's why you're getting the error.

**Comment by vikmn** [comment]
Just tried it locally and seems like a bit more detail on the error. But cant seem to find the scss file mentioned
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'style.scss':
                    Undefined mixin 'box-sizing'. on line 138
jekyll 3.4.2 | Error:  Undefined mixin 'box-sizing'. on line 138

**Comment by mmistakes** [comment]
Verify you have all the Sass partials that are in this repo. Sounds like you're missing some. 

If you have a public repo I can troubleshoot better.

**Comment by vikmn** [comment]
Hi michael,
I managed to discover the issue. As i was applying the theme to an existing
site i had inadvertently missed out on a style.scss file which was in the
root folder. Having deleted it i managed to resolve the issue.
