### ISSUE TITLE
Include creation of navigation.yml when "starting fresh"

### ISSUE THREAD

**Issue by mchelen** [mmistakes/so-simple-theme#270]
- [x] This is a feature request or enhancement.

I followed the guide for installing as a remote theme, and created the files as documented in https://github.com/mmistakes/so-simple-theme#starting-fresh but it took me awhile to figure out that I needed to create `_data/navigation.yml` to get the menu bar to appear. I know there is a lot of optional config files documented later, but maybe this file should be mentioned as one of the required config steps?

**Comment by mmistakes** [comment]
Happy to look a PR if you want to improve the documentation.

There's a [navigation specific section](https://github.com/mmistakes/so-simple-theme#navigation) already, I just assumed if someone was looking for info on how to create the nav they'd go there.

**Comment by mmistakes** [comment]
Also worth noting, if you're using the theme gem version, all of the root `_data` files are automatically included. So you don't have to create them.

There's a limitation with how Jekyll handles these files right now. They don't bundle in `_data` like `_layouts`, `_includes`, `_sass`. The theme uses a plugin called `jekyll-data` to do this, but it isn't supported with GitHub Pages. Which is why you have to manually copy those files.
