### ISSUE TITLE
Showing the date of last modified

### ISSUE THREAD

**Issue by alxddh** [mmistakes/so-simple-theme#351]
## Summary

I noticed that you have used the `last_modified_at` front matter in many Markdown files, but you didn't show the date in the final generated HTML files. I think that showing the last-modified-date to readers is good.

## Motivation

- https://www.shoutmeloud.com/show-last-modified-date-wordpress.html

**Comment by mmistakes** [comment]
It's purposely left off to avoid cluttering the page.

**Comment by djkeh** [comment]
I've been aware of this change since I upgraded my blog to version 3 last time. It was quite a while ago. As @mmistakes commented, it clearly looked as it's done on purpose. Sometimes I miss modified date as I thought I needed that information, however, that thinking is not present on my head anymore. I stand up for the current design. It looks fairly good and enough now.
